import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import {
  MatButtonModule,
  MatMenuModule,
  MatToolbarModule,
  MatIconModule,
  MatCardModule,
  MatFormFieldModule,
  MatInputModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatRadioModule,
  MatSelectModule,
  MatOptionModule,
  MatListModule,
  MatSidenavModule,
  MatSlideToggleModule,
  ErrorStateMatcher,
  ShowOnDirtyErrorStateMatcher,
  MatGridListModule,
  MatSnackBarModule,
  MatExpansionModule, 
  MatTabsModule, 
  MatTableModule, 
  MatCheckboxModule,
  MatPaginatorModule
} from '@angular/material';
import {AngularDateTimePickerModule} from 'angular2-datetimepicker';
import {
    AccordionModule,
    ButtonModule,
    CalendarModule, ConfirmDialogModule,
    DialogModule,
    DragDropModule, EditorModule, GMapModule, InputTextareaModule,
    InputTextModule, OverlayPanelModule, PanelModule,
    PickListModule, StepsModule
} from 'primeng/primeng';
import {MenuItem} from 'primeng/api';
import {ToastModule} from 'primeng/toast';
import {TableModule} from 'primeng/table';

@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    MatButtonModule,
    MatMenuModule,
    MatToolbarModule,
    MatIconModule,
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatRadioModule,
    MatSelectModule,
    MatOptionModule,
    MatListModule,
    MatSidenavModule,
    MatSlideToggleModule,
    MatGridListModule,
    MatSnackBarModule,
    MatExpansionModule, 
    MatTabsModule, 
    MatTableModule, 
    MatCheckboxModule,
    MatPaginatorModule,
    AngularDateTimePickerModule,
    AccordionModule,
    CalendarModule,
    PickListModule,
    DragDropModule,
    ToastModule,
      TableModule,
      DialogModule,
      InputTextModule,
      ButtonModule,
      PanelModule,
      EditorModule,
      InputTextareaModule,
      ConfirmDialogModule,
      StepsModule,
      GMapModule,
      OverlayPanelModule
  ],
  declarations: [],
  exports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    MatButtonModule,
    MatMenuModule,
    MatToolbarModule,
    MatIconModule,
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatRadioModule,
    MatSelectModule,
    MatOptionModule,
    MatListModule,
    MatSidenavModule,
    MatSlideToggleModule,
    MatGridListModule,
    MatSnackBarModule,
    MatExpansionModule,
    MatTabsModule,
    MatTableModule,
    MatCheckboxModule,
    MatPaginatorModule,
    AngularDateTimePickerModule,
    AccordionModule,
    CalendarModule,
    PickListModule,
    DragDropModule,
    ToastModule,
      TableModule,
      DialogModule,
      InputTextModule,
      ButtonModule,
      PanelModule,
      EditorModule,
      InputTextareaModule,
      ConfirmDialogModule,
      StepsModule,
      GMapModule,
      OverlayPanelModule
  ],
  providers: [
    { provide: ErrorStateMatcher, useClass: ShowOnDirtyErrorStateMatcher }
  ]
})
export class UiModule {}
