import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import {
  MatButtonModule,
  MatMenuModule,
  MatToolbarModule,
  MatIconModule,
  MatCardModule,
  MatFormFieldModule,
  MatInputModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatRadioModule,
  MatSelectModule,
  MatOptionModule,
  MatListModule,
  MatSidenavModule,
  MatSlideToggleModule,
  ErrorStateMatcher,
  ShowOnDirtyErrorStateMatcher,
  MatGridListModule,
  MatSnackBarModule,
  MatExpansionModule, 
  MatTabsModule, 
  MatTableModule, 
  MatCheckboxModule,
  MatPaginatorModule
} from '@angular/material';
import {AngularDateTimePickerModule} from 'angular2-datetimepicker';
import {
    AccordionModule,
    ButtonModule,
    CalendarModule,
    ConfirmDialogModule,
    DialogModule,
    DragDropModule,
    EditorModule,
    GMapModule,
    InputTextModule,
    OverlayPanelModule,
    PanelModule,
    PickListModule,
    StepsModule,
    CardModule,
    TabViewModule,
    ToolbarModule,
    SidebarModule,
    TooltipModule,
    PasswordModule
} from 'primeng/primeng';
import { ToastModule } from 'primeng/toast';
import { TableModule } from 'primeng/table';
import { DataViewModule } from 'primeng/dataview';
import { PaginatorModule } from 'primeng/paginator';
import { MessageService } from 'primeng/api';
import { InputTextareaModule } from 'primeng/inputtextarea';
import { ProgressSpinnerModule } from 'primeng/progressspinner';

@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    MatButtonModule,
    MatMenuModule,
    MatToolbarModule,
    MatIconModule,
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatRadioModule,
    MatSelectModule,
    MatOptionModule,
    MatListModule,
    MatSidenavModule,
    MatSlideToggleModule,
    MatGridListModule,
    MatSnackBarModule,
    MatExpansionModule, 
    MatTabsModule, 
    MatTableModule, 
    MatCheckboxModule,
    MatPaginatorModule,
    AngularDateTimePickerModule,
    AccordionModule,
    CalendarModule,
    PickListModule,
    DragDropModule,
    ToastModule,
    TableModule,
    DialogModule,
    InputTextModule,
    ButtonModule,
    PanelModule,
    EditorModule,
    InputTextareaModule,
    ConfirmDialogModule,
    StepsModule,
    GMapModule,
    OverlayPanelModule,
    CardModule,
    TabViewModule,
    ToolbarModule,
    SidebarModule,
    TooltipModule,
    PasswordModule,
    DataViewModule,
    PaginatorModule,
    ProgressSpinnerModule
  ],
  declarations: [],
  exports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    MatButtonModule,
    MatMenuModule,
    MatToolbarModule,
    MatIconModule,
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatRadioModule,
    MatSelectModule,
    MatOptionModule,
    MatListModule,
    MatSidenavModule,
    MatSlideToggleModule,
    MatGridListModule,
    MatSnackBarModule,
    MatExpansionModule,
    MatTabsModule,
    MatTableModule,
    MatCheckboxModule,
    MatPaginatorModule,
    AngularDateTimePickerModule,
    AccordionModule,
    CalendarModule,
    PickListModule,
    DragDropModule,
    ToastModule,
    TableModule,
    DialogModule,
    InputTextModule,
    ButtonModule,
    PanelModule,
    EditorModule,
    InputTextareaModule,
    ConfirmDialogModule,
    StepsModule,
    GMapModule,
    OverlayPanelModule,
    CardModule,
    TabViewModule,
    ToolbarModule,
    SidebarModule,
    TooltipModule,
    PasswordModule,
    DataViewModule,
    PaginatorModule,
    ProgressSpinnerModule
  ],
  providers: [
    MessageService,
    { provide: ErrorStateMatcher, useClass: ShowOnDirtyErrorStateMatcher }
  ]
})
export class UiModule {}
